labels = [
  { name: 'Academic Fraud', description: 'Sites that promote educational fraud, including but not limited to plagiarism and cheating.' },
  { name: 'Adult Themes', description: 'Sites that are adult in nature and are not defined in other rating categories. Note: This category should only be turned on if you want to be very restrictive on your network.' },
  { name: 'Advertising', description: 'Sites that serve advertising. This category is specifically aimed at identifying ad servers. Note: not available as a filter at this time.' },
  { name: 'Alcohol', description: 'Sites about alcohol use, commercial and otherwise.' },
  { name: 'Anime/Manga/Webcomic', description: 'Sites that host online comics, cartoons and graphic novels.' },
  { name: 'Auctions', description: 'Sites for buying and selling via auction.' },
  { name: 'Automotive', description: 'Sites about automobiles, including manufacturers, news, reviews and hobbyist information.' },
  { name: 'Blogs', description: 'Sites that are personal or group journals, diaries or publications.' },
  { name: 'Business Services', description: 'Sites for corporations and businesses of all sizes, especially company websites.' },
  { name: 'Chat', description: 'Sites where you can chat in real-time with groups of people. Includes IRC and video chat sites.' },
  { name: 'Classifieds', description: 'Sites for buying and selling (or bartering) goods and services. Includes sites with real estate and housing listings.' },
  { name: 'Dating', description: 'Sites for meeting other people.' },
  { name: 'Drugs', description: 'Sites about illegal or recreational drug use.' },
  { name: 'Ecommerce/Shopping', description: 'Sites that are online stores for products and services.' },
  { name: 'Educational Institutions', description: 'Sites for schools, covering all age levels and types.' },
  { name: 'File Storage', description: 'Sites that offer space for hosting, sharing and backup of digital files.' },
  { name: 'Financial Institutions', description: 'Sites for banks, brokerages, trusts and other financial organizations.' },
  { name: 'Forums/Message boards', description: 'Sites with discussions, including bulletin boards, message boards and forums.' },
  { name: 'Gambling', description: 'Sites that offer gambling or information about gambling.' },
  { name: 'Games', description: 'Sites that offer game play and information about games (news, tips, cheat codes).' },
  { name: 'Government', description: 'Sites operated by government agencies, including city, state, regional, county and federal levels.  Also includes .mil domains.' },
  { name: 'Hate/Discrimination', description: 'Sites that promote intolerance based on gender, age, race, nationality, religion, sexual orientation or other group identities.' },
  { name: 'Health and Fitness', description: 'Sites that offer information about health care and health services. Includes fitness related sites and information about health and fitness.' },
  { name: 'Humor', description: 'Sites that are intended to be funny or humorous.' },
  { name: 'Instant Messaging', description: 'Sites that offer access or software to communicate in real-time with other individuals.' },
  { name: 'Jobs/Employment', description: 'Sites that offer job listings, resume services, interview coaching and similar employment-related services.' },
  { name: 'Lingerie/Bikini', description: 'Sites displaying or dedicated to lingerie/bikini that could be considered adult-only.' },
  { name: 'Movies', description: 'Sites that promote movies or offer movie watching online.' },
  { name: 'Music', description: 'Sites about music, including news, band and fan information.' },
  { name: 'News/Media', description: 'Sites that offer news and information, including newspapers, broadcasters and other publishers.' },
  { name: 'Non-Profits', description: 'Sites for non-profit or charity organizations and services.' },
  { name: 'Nudity', description: 'Sites that provide images or representations of nudity.' },
  { name: 'P2P/File sharing', description: 'Sites that facilitate the sharing of digital files between individuals, especially via peer-to-peer software, including torrent sites.' },
  { name: 'Parked Domains', description: 'Sites that are placeholders "parked" for future use. Current uses may include single-page advertising sites.' },
  { name: 'Photo Sharing', description: 'Sites for sharing photographs, as individual images, galleries and albums.' },
  { name: 'Podcasts', description: 'Sites that offer podcasts, digital media files distributed over the Internet, often using syndication feeds, for playback on portable media players and personal computers. Both audio and video podcasts are included.' },
  { name: 'Politics', description: 'Sites about politics, politicians, political parties and organizations. Government sites are separate.' },
  { name: 'Pornography', description: 'Anything relating to pornography, including mild depiction, soft pornography or hard-core pornography.' },
  { name: 'Portals', description: 'Sites that offer gateways to the Internet as a whole, often including bundled services on their own site.' },
  { name: 'Proxy/Anonymizer', description: 'Sites providing proxy bypass information or services. Also, sites that allow the user to surf the net anonymously, including sites that allow the user to send anonymous emails.' },
  { name: 'Radio', description: 'Sites that offer online radio listening or promote radio stations.' },
  { name: 'Religious', description: 'Sites about religion, religious teachings and groups, and spirituality.' },
  { name: 'Research/Reference', description: 'Sites such as encyclopedias, dictionaries as well as other research-related resources.' },
  { name: 'Search Engines', description: 'Sites that offer result listings based on keywords.' },
  { name: 'Sexuality', description: 'Sites that provide information, images or implications of bondage, sadism, masochism, fetish, beating, body piercing or self-mutilation. This category is not intended for LGBT related sites that do not fall under the aforementioned criteria.' },
  { name: 'Social Networking', description: 'Sites that promote interaction and networking between people.' },
  { name: 'Software/Technology', description: 'Sites about computing, cloud computing, hardware and technology, including news, information, code and vendor information.' },
  { name: 'Sports', description: 'Sites about sports of all kinds, from professional to amateur, from news to league information and schedules. Includes Martial Arts and MMA related sites.' },
  { name: 'Tasteless', description: 'Sites that contain information on such subjects as mutilation, torture, horror, or the grotesque. Includes Pro-Anorexia and Pro-Suicide related sites.' },
  { name: 'Television', description: 'Sites that promote television shows or offer television watching online.' },
  { name: 'Tobacco', description: 'Sites about tobacco use and related products, commercial and otherwise.' },
  { name: 'Travel', description: 'Sites with travel information and services, including reservations for airlines, cars, hotels, vacations, and trips.' },
  { name: 'URL Shortener', description: 'An online application or service that converts a regular URL into a condensed format.' },
  { name: 'Video Sharing', description: 'Sites for sharing video content.' },
  { name: 'Visual Search Engines', description: 'Sites for searching for images based on keywords.' },
  { name: 'Weapons', description: 'Sites about weapons, commercial and otherwise.' },
  { name: 'Web Spam', description: 'Redirect targets containing unwanted Sweepstakes/Survey/Advertisements for free merchandise, pharmaceutical spam or Rolex distributions.' },
  { name: 'Webmail', description: 'Sites that offer the ability to send or receive email.' }
]

labels.each_with_index do |label_hash, i|
  label = Label.find_or_create_by(
    name: label_hash[:name],
    description: label_hash[:description],
    licence: Licence.first
  )
end
