class App < ApplicationRecord
  # needed to load uuid that is generated by postgres
  # https://github.com/rails/rails/issues/21627#issuecomment-142625429
  # https://www.devmynd.com/blog/db-generated-values-and-activerecord/
  after_create :reload

  jsonb_accessor :os, (::ENVProxy.required_array('OPERATING_SYSTEMS')
                                 .each_with_object({}) do |os, h|
                                   h[os] = [:boolean, default: false]
                                 end)

  belongs_to :user
  has_many :stamps, as: :stampable

  validates_presence_of %i[description link name user uuid]
  validate :supports_one_or_more_operating_systems

  def operating_systems
    @operating_systems ||= ENVProxy.required_array('OPERATING_SYSTEMS')
  end

  def supports_one_or_more_operating_systems
    counts = operating_systems.map { |os| send("#{os}?") }
                              .group_by(&:itself)
                              .transform_values(&:count)

    return true if counts[true].present?

    os_hash = operating_systems.each_with_object({}) { |f, h| h[f] = send(f) }
    errors.add(:os, "- at least one operating system must be supported by the app #{os_hash}")
  end
end
